/*
 * generated by Xtext 2.17.1
 */
package sdu.mdsd.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MathinterpreterUiModule extends AbstractMathinterpreterUiModule {
	def Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return ExpEObjectHoverProvider }
}


